project:
  type: website
  output-dir: docs

website:
  title: "Mackenna Amole - CPLN 5920 Portfolio"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: Labs
        menu:
        - href: labs/lab_0/lab_0.qmd
          text: "Lab 0: dplyr Basics"
        - href: labs/lab_1/lab_1.qmd
          text: "Lab 1: Census Data Exploration"
     # - text: Weekly Notes
     #   menu:
      #  - href: weeklynotes/path/path
       #   text: "Week 1"
      

format:
  html:
    theme: cosmo
    toc: true
    code-fold: true

execute:
  freeze: auto
